### ISSUE TITLE
[20190516]Windows 7 update更新失敗 #2

### ISSUE THREAD

**Issue by oecshikai** [oecAllis/infra-ticket#27]
1.Vivian - Windows 7 更新失敗，導致系統復原需花User一個小時以上時間。
2.anita - Windows 7 更新失敗，導致系統無法開機，須修復開機檔。

**Comment by Helen215** [comment]
1. KHH Genny(#35) - Windows 7 更新失敗，導致系統復原需花User一個小時以上時間。
   原因：Windows 安全性更新for Win10 (KB2310138), 故無法在Win 7更新成功
   解決：需關閉更新檔並隱藏不再做更新，及選擇「檢查更新, 但是讓我選擇是否要下載及安裝它們」
